### ISSUE TITLE
Error Whenever I try to download

### ISSUE THREAD

**Issue by BCNOFNeNaMg** [CelestialCartographers/Ahorn#10]
I have installed Julia 1.1.0, and yet whenever I try to install Ahorn there is an error during precompiling. It leaves this error log: 
ERROR: ArgumentError: Package Ahorn [10a6d802-9bc0-11e8-304a-1bca7ec2ebad] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] _require(::Base.PkgId) at .\loading.jl:929
 [2] require(::Base.PkgId) at .\loading.jl:858
 [3] require(::Module, ::Symbol) at .\loading.jl:853

Any help would be appreciated. Thanks!

**Comment by Vexatos** [comment]
Most errors related to this have been fixed some months ago.
