### ISSUE TITLE
Failed to Precompile Gtk

### ISSUE THREAD

**Issue by BlueNine9** [CelestialCartographers/Ahorn#12]
```
Precompiling project...
ERROR: LoadError: LoadError: error compiling top-level scope: could not load library "libgobject-2.0-0"
The specified module could not be found.

Stacktrace:
 [1] include at .\boot.jl:326 [inlined]
 [2] include_relative(::Module, ::String) at .\loading.jl:1038
 [3] include at .\sysimg.jl:29 [inlined]
 [4] include(::String) at C:\Fakepath\.julia\packages\Gtk\RwVPb\src\Gtk.jl:2
 [5] top-level scope at none:0
 [6] include at .\boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1038
 [8] include(::Module, ::String) at .\sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:328 [inlined]
 [11] eval(::Expr) at .\client.jl:404
 [12] top-level scope at .\none:3
in expression starting at C:\Fakepath\.julia\packages\Gtk\RwVPb\src\GLib\GLib.jl:49
in expression starting at C:\Fakepath\.julia\packages\Gtk\RwVPb\src\Gtk.jl:7
```
Used Julia 1.1 and windows 10.

**Comment by Ngakk** [comment]
Ran in to the same problem, found fix on https://github.com/JuliaPackaging/WinRPM.jl/issues/127

**Comment by Mystery-Manager** [comment]
> Ran in to the same problem, found fix on [JuliaPackaging/WinRPM.jl#127](https://github.com/JuliaPackaging/WinRPM.jl/issues/127)

How exactly do you use this?

**Comment by Ngakk** [comment]
You go to C:\users\youruser\.julia\packages\WinRPM\sources.cs and change the number 42.2 on both lines to 42.3, then open the julia terminal and write 'Using Pkg; Pkg.build("Gtk")' to check if there are no errors, if that works you should be able to run the ahorn installer

**Comment by Mystery-Manager** [comment]
Thanks, but when I tried that it was marked as read-only.

**Comment by Mystery-Manager** [comment]
Haha, nvmd I'm stupid

**Comment by Mystery-Manager** [comment]
Huh, that's not working for me.

julia> Using Pkg; Pkg.build("Gtk")
ERROR: syntax: extra token "Pkg" after end of expression

**Comment by Ngakk** [comment]
Try 'using' on all lowercase `using Pkg; Pkg.build("Gtk")`

**Comment by Vexatos** [comment]
No longer relevant and fixed some months ago.
