### ISSUE TITLE
Error building Gtk and Cairo, Endless loop! Please help!

### ISSUE THREAD

**Issue by GamerXLPro** [CelestialCartographers/Ahorn#14]
Hello! I've been over 1 month trying to fix this! went into discord to ask help, tried everything and i couldnt! I really need help!

The problem is that always gives error when trying to build Cairo or GTK, no matter what (using NSIS)

This is the error log!

Error: Error building `Cairo`:
│ ┌ Warning: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:148
│ ┌ Warning: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:148
│ [ Info: Updating WinRPM package list
│ [ Info: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/repodata/repomd.xml
│ ┌ Warning: Unknown download failure, error code: 2148270105
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/repodata/repomd.xml
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: Unknown download failure, error code: 2148270105
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/repodata/repomd.xml
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: Unknown download failure, error code: 2148270105
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/repodata/repomd.xml
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: Unknown download failure, error code: 2148270105
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/repodata/repomd.xml
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: Unknown download failure, error code: 2148270105
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/repodata/repomd.xml
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/repodata/repomd.xml
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:154
│ [ Info: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.3/repodata/repomd.xml
│ ┌ Warning: Unknown download failure, error code: 2148270105
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.3/repodata/repomd.xml
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: Unknown download failure, error code: 2148270105
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.3/repodata/repomd.xml
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: Unknown download failure, error code: 2148270105
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.3/repodata/repomd.xml
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: Unknown download failure, error code: 2148270105
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.3/repodata/repomd.xml
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: Unknown download failure, error code: 2148270105
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.3/repodata/repomd.xml
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.3/repodata/repomd.xml
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:154
│ ERROR: LoadError: None of the selected providers could satisfy library group cairo
│ Use BinDeps.debug(package_name) to see available providers
│
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] satisfy!(::BinDeps.LibraryGroup, ::Array{DataType,1}) at C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\BinDeps\ZEval\src\dependencies.jl:915
│  [3] satisfy!(::BinDeps.LibraryGroup) at C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\BinDeps\ZEval\src\dependencies.jl:874
│  [4] top-level scope at C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\BinDeps\ZEval\src\dependencies.jl:977
│  [5] include at .\boot.jl:326 [inlined]
│  [6] include_relative(::Module, ::String) at .\loading.jl:1038
│  [7] include(::Module, ::String) at .\sysimg.jl:29
│  [8] include(::String) at .\client.jl:403
│  [9] top-level scope at none:0
│ in expression starting at C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\Cairo\CXPG1\deps\build.jl:165
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075
  Building Gtk ─────→ `C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\Gtk\RwVPb\deps\build.log`
┌ Error: Error building `Gtk`:
│ ┌ Warning: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:148
│ ┌ Warning: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
│ └ @ WinRPM C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:148
│ ERROR: LoadError: Package candidate for glib2-tools not found
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] select(::WinRPM.Packages{Array{LibExpat.ETree,1}}, ::String) at C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:258
│  [3] #install#18(::Bool, ::Function, ::Array{String,1}, ::String) at C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\WinRPM\Y9QdZ\src\WinRPM.jl:377
│  [4] #install at .\none:0 [inlined] (repeats 2 times)
│  [5] top-level scope at C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\Gtk\RwVPb\deps\build.jl:30
│  [6] include at .\boot.jl:326 [inlined]
│  [7] include_relative(::Module, ::String) at .\loading.jl:1038
│  [8] include(::Module, ::String) at .\sysimg.jl:29
│  [9] include(::String) at .\client.jl:403
│  [10] top-level scope at none:0
│ in expression starting at C:\Users\Franco Padin\AppData\Local\CelestialCartographers\Ahorn\juliapkg\packages\Gtk\RwVPb\deps\build.jl:24
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075

Please, if there is any way i can fix this, no matter what severe it is, tell me! Please!

EDIT: Thanks for not replying! Please i need help

**Comment by Vexatos** [comment]
No longer relevant and fixed some months ago.
