### ISSUE TITLE
Unable to start ahorn

### ISSUE THREAD

**Issue by ImGameDev** [CelestialCartographers/Ahorn#19]
Getting this error while trying to run ahorn.sh using Julia
`
ERROR: LoadError: syntax: extra token """ after end of expression
Stacktrace:
 [1] top-level scope at /Users/---/---/ahorn.sh:2
 [2] include(::Module, ::String) at ./Base.jl:377
 [3] exec_options(::Base.JLOptions) at ./client.jl:288
 [4] _start() at ./client.jl:484
in expression starting at /Users/---/---/ahorn.sh:2
`

**Comment by Cruor** [comment]
Why are you including the .sh through Julia REPL instead of running it via the terminal?

**Comment by ImGameDev** [comment]
Alright! 
So I ran it through the terminal and this is what I get. My terminal got terminated after this
`
If this is the first time running Ahorn, this might take a while.
The window might stay blank for a long time, this is normal as packages are precompiling in the background.
`

**Comment by Kavikavika** [comment]
I'm having the same issue as ImGameDev and Ahorn won't launch, I have successfully installed Ahorn through Julia on Mac OS and I get the same message in my terminal window with nothing happening.  I looked into the paths and I'm not having any success.

**Comment by Cruor** [comment]
What does the error log in `$HOME/.config/Ahorn/error.log` say? where $HOME is your home folder. Hidden files/folders can be shown by using `command shift .`.

**Comment by Kavikavika** [comment]
./ahorn.sh: line 4: julia: command not found

**Comment by Cruor** [comment]
The script assumes Julia is in PATH. How exactly did you install Ahorn? I would highly recommend just adding Julia to PATH, but you can also put the full path to Julia into the shell script yourself.
