### ISSUE TITLE
Ahorn fails to build on macOS from Julia failing to get pangocairo and gtk dependencies 

### ISSUE THREAD

**Issue by thatrs** [CelestialCartographers/Ahorn#2]
Here are the error outputs:
```
=========================================[ ERROR: Cairo ]=========================================

LoadError: Provider Homebrew.HB failed to satisfy dependency pangocairo
while loading /Users/thatrs/.julia/v0.6/Cairo/deps/build.jl, in expression starting on line 161

==================================================================================================

==========================================[ ERROR: Gtk ]==========================================

LoadError: Provider Homebrew.HB failed to satisfy dependency gtk
while loading /Users/thatrs/.julia/v0.6/Gtk/deps/build.jl, in expression starting on line 63

==================================================================================================

```

**Comment by Vexatos** [comment]
Try reinstalling Cairo and Gtk
```julia
using Homebrew

Homebrew.rm("Cairo")
Homebrew.add("Cairo")
Homebrew.rm("Gtk")
Homebrew.add("Gtk")

Pkg.build("Cairo")
Pkg.build("Gtk")
```

**Comment by thatrs** [comment]
When I try to install Gtk after installing Homebrew, it gives an error saying that the gtk formula is missing from the taps folder.

```
ERROR: SystemError: opening file /Users/thatrs/.julia/v0.6/Homebrew/deps/usr/Library/Taps/homebrew/homebrew-core/Formula/Gtk.rb: No such file or directory
```

**Comment by thatrs** [comment]
I also tried using the latest version of Julia (0.7.0) but it still gives the same dependency errors and the same missing formula error when trying to install or reinstall Gtk.

**Comment by thatrs** [comment]
I was able to build Cairo after manually installing pango with homebrew before deleting the julia files and restarting the installation file, but the gtk formula was still missing.

**Comment by Vexatos** [comment]
Ahorn won't work on Julia 0.7.
Could you try manually installing gtk? The package should be called `gtk+3`

**Comment by thatrs** [comment]
It still gave the same error as before on Julia 0.6.

**Comment by leo60228** [comment]
Why is this in my email

**Comment by leo60228** [comment]
This seems like a Homebrew bug. Try

```
brew update
```

, that may fix it. Also try (re)installing Homebrew (from [brew.sh](https://brew.sh)).

**Comment by leo60228** [comment]
Also, just making sure: you typed 
```
using Homebrew
Homebrew.add("gtk+3")`
```
exactly, right? Not `Homebrew.add("Gtk+3")` or `Homebrew.add("Gtk")`?

**Comment by leo60228** [comment]
@Vexatos This issue hasn't been updated in a while, and will likely be fixed in the next version with the removal of BinDeps. Can you close it?
