### ISSUE TITLE
Can't seem to get Ahorn working.

### ISSUE THREAD

**Issue by SpareUmbrella** [CelestialCartographers/Ahorn#21]
I don't know much about computers, and when trying to get Ahorn to load, I get this error message in the log.

> ERROR: ArgumentError: Package Ahorn not found in current path:
> - Run `import Pkg; Pkg.add("Ahorn")` to install the Ahorn package.
> 
> Stacktrace:
>  [1] require(::Module, ::Symbol) at .\loading.jl:887

I tried running this but it doesn't seem to work, Help?

**Comment by Cruor** [comment]
Some other package failed during installation. Comment at https://github.com/CelestialCartographers/Ahorn/issues/18#issuecomment-601267641 should be relevant for you, or you can grab the NSIS installer on the Discord server, assuming you are using Windows.
