### ISSUE TITLE
Can't seem to get Ahorn working

### ISSUE THREAD

**Issue by Parrotapocalypse** [CelestialCartographers/Ahorn#23]
I used the NSIS installer to get Ahorn and it worked, but when I opened it later it began loading (showing the bird animation) then it and the terminal closed. I have tried multiple times and gotten the same result; the only warning that seems to show up is: ```(julia.exe:14044): Gtk-WARNING **: 20:55:34.786: Theme parsing error: gtk-win32-base.css:1043:59: Junk at end of value for background-image```

**Comment by Cruor** [comment]
That warning doesn't matter. If you haven't started it properly before just be patient, it takes some time.

**Comment by Cruor** [comment]
Closing as this is not really a issue and lack of activity.
