### ISSUE TITLE
cant open or complete installing ahorn

### ISSUE THREAD

**Issue by NOUR1F** [CelestialCartographers/Ahorn#25]
yesterday on 2020/08/12 i tried installing ahorn , always a problems or errors occured like , not able to install julia 1.4.1 and setuping ect , i solved the problem and downloaded julia 1.4.2 manually and it accepted it i guess , after that now , it says this to me and idk what should i do : ( Activating environment at `C:\Users\NOUR1F\AppData\Local\Ahorn\env\Project.toml`
ERROR: ArgumentError: Package Ahorn not found in current path:
- Run `import Pkg; Pkg.add("Ahorn")` to install the Ahorn package.
Stacktrace:
 [1] require(::Module, ::Symbol) at .\loading.jl:892)

 and when i try to open julie and type (import Pkg; Pkg.add("Ahorn"))
it says : {registry at  `c:/users/NOUR1F/.julia/registries/general`
             git-repo  `https://github.com/juliaregistries/general.git`
              ERROR: the following package names could not be resolved:
               * Ahorn (not found in project , manifest or registery)}

what should i do now then?

**Comment by Cruor** [comment]
Some other package failed during installation. https://github.com/CelestialCartographers/Ahorn/issues/18#issuecomment-601267641 should be relevant for you. If the installer keeps failing we have alternative solutions available on Discord.

**Comment by NOUR1F** [comment]
![image](https://user-images.githubusercontent.com/69647368/90182797-2d7cd500-ddbb-11ea-85f0-f57c505eecc1.png)
i did what  u said and its stuck now on this for a 2 hour now ig

**Comment by NOUR1F** [comment]
and now it still shows the same error msg again

**Comment by NOUR1F** [comment]
![image](https://user-images.githubusercontent.com/69647368/90244525-9acf4b00-de39-11ea-95bc-5c149b10b950.png)
ok what should i do now? thats new

**Comment by Cruor** [comment]
Are you running Windows 7 or a hardly updated Windows 10? Attempt [these instructions](https://julialang.org/downloads/platform/#windows_7_windows_server_2012_installation_notes) or use the alternative installer on the Celeste Discord.

**Comment by NOUR1F** [comment]
well i run windows 7 , i have a problem and i cant acsess discord these days so can you send me the installer? i tried the instructions too and didnt work

**Comment by Cruor** [comment]
The NSIS installer changes with every major / bug fixed version of Ahorn. I would rather not have a link of that available on Github history, as someone will figure out it's a good idea to use without understanding the side effects. If I considered it a good idea it would already be linked in either the README or released on Github.

**Comment by NOUR1F** [comment]
alright what should i do?
