### ISSUE TITLE
Project.toml errors

### ISSUE THREAD

**Issue by Whyisthisusernamenottaken** [CelestialCartographers/Ahorn#26]
I had an error before about project.toml. I quickly realised that the file was incomplete so i just pasted the project.toml from the git repo. Same thing for the manifest.toml. But it still did not work. Anyways, here is the error log : 
Activating environment at `C:\Users\rayane\AppData\Local\Ahorn\env\Project.toml`
ERROR: ArgumentError: Package Ahorn [10a6d802-9bc0-11e8-304a-1bca7ec2ebad] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] _require(::Base.PkgId) at .\loading.jl:998
 [2] require(::Base.PkgId) at .\loading.jl:927
 [3] require(::Module, ::Symbol) at .\loading.jl:922
I ran Pkg.instanstiate but it still did not work. Julia told me this :                   
ERROR: UndefVarError : Pkg not defined 
Stacktrace :  [1] top-level scope at REPL[1] :1
Sorry for asking but, how can you define the Pkg? I added ahorn in the terminal but it tells me that Ahorn was not found in project, manifest, or registry (obviously). Hopefully you can point me in the right direction here.

**Comment by Whyisthisusernamenottaken** [comment]
When installing, these were the errors.
<img width="402" alt="uy" src="https://user-images.githubusercontent.com/69699546/90321296-5fef1500-df16-11ea-92ea-e97a00b6ca73.PNG">
<img width="398" alt="uy2" src="https://user-images.githubusercontent.com/69699546/90321299-63829c00-df16-11ea-8cf8-0776d1bc7b3a.PNG">
<img width="395" alt="uy4" src="https://user-images.githubusercontent.com/69699546/90321310-6b424080-df16-11ea-8066-9c1ddc44ea54.PNG">
<img width="395" alt="uy3" src="https://user-images.githubusercontent.com/69699546/90321311-6b424080-df16-11ea-865e-8be477572615.PNG">

**Comment by Whyisthisusernamenottaken** [comment]
<img width="402" alt="uy" src="https://user-images.githubusercontent.com/69699546/90321372-0b986500-df17-11ea-94ff-29e6d2371bb7.PNG">
<img width="395" alt="uy3" src="https://user-images.githubusercontent.com/69699546/90321381-16eb9080-df17-11ea-81db-ae03eb7c8dd9.PNG">
<img width="398" alt="uy2" src="https://user-images.githubusercontent.com/69699546/90321382-16eb9080-df17-11ea-9101-6672ba839374.PNG">
<img width="395" alt="uy4" src="https://user-images.githubusercontent.com/69699546/90321383-1a7f1780-df17-11ea-9196-ce7d218995b4.PNG">

**Comment by Cruor** [comment]
Are you running Windows 7 or a hardly updated Windows 10? Attempt [these instructions](https://julialang.org/downloads/platform/#windows_7_windows_server_2012_installation_notes) or use the alternative installer on the Celeste Discord.
