### ISSUE TITLE
Error trying to install 

### ISSUE THREAD

**Issue by JACOBFRANTZ** [CelestialCartographers/Ahorn#27]
Error: https://hastebin.com/feyaqurame.php

This occurs whenever I try to run the ahorn.bat. Instead of installing or opening Ahorn, it says press any key to continue, then closes out of the tab.

I tried doing the other install method using Julia, but I ended up getting an error for not having homebrew and gtk, Homebrew not being available on windows.

**Comment by Cruor** [comment]
Your CPU doesn't support a feature one of our dependencies use. See [this issue](https://github.com/CelestialCartographers/Ahorn/issues/16).

Closing this issue since it's a duplicate.
