### ISSUE TITLE
Triggers column not rendering?

### ISSUE THREAD

**Issue by asparagii** [CelestialCartographers/Ahorn#31]
As the title suggests, the triggers column is empty on my fresh install of Ahorn.

![image](https://user-images.githubusercontent.com/15233143/103297668-1a307600-49f9-11eb-836c-1cb8301316cf.png)
The "Bloom Fade Trigger" material is selected - as in, I can place it - and I have no way to pick any other trigger material.

In addition, the Entities' Material column only contains two elements: "Floaty Space Block" and "Player (Spawn Point)".
![image](https://user-images.githubusercontent.com/15233143/103299479-ee16f400-49fc-11eb-8f03-158a33e791e7.png)

Everything else seems to be OK.

I'm using Ahorn with Hash f5398ec - which should be the latest available version. I'm also using Windows 10.

This is my first time trying out Ahorn, so it's very likely to be my fault - although I don't think I'm doing anything different than what I've seen other users doing on youtube/twitch.

Here's the error.log file content, although upon restarting these errors don't show up and the column is still empty.

```
(julia.exe:10300): Gtk-WARNING **: 14:38:10.479: Theme parsing error: gtk-win32-base.css:1043:59: Junk at end of value for background-image

(julia.exe:10300): Gtk-WARNING **: 17:01:31.762: Negative content width -7 (allocation 1, extents 4x4) while allocating gadget (node button, owner GtkButton)

(julia.exe:10300): Gtk-WARNING **: 17:01:33.309: Negative content width -1 (allocation 7, extents 4x4) while allocating gadget (node button, owner GtkButton)

(julia.exe:10300): Gtk-WARNING **: 17:01:33.938: Negative content width -6 (allocation 2, extents 4x4) while allocating gadget (node button, owner GtkButton)

(julia.exe:10300): Gtk-WARNING **: 17:01:33.958: Negative content width -7 (allocation 1, extents 4x4) while allocating gadget (node button, owner GtkButton)

(julia.exe:10300): Gtk-WARNING **: 17:01:34.545: Negative content width -5 (allocation 3, extents 4x4) while allocating gadget (node button, owner GtkButton)

(julia.exe:10300): Gtk-WARNING **: 17:01:34.562: Negative content width -2 (allocation 6, extents 4x4) while allocating gadget (node button, owner GtkButton)

(julia.exe:10300): Gtk-WARNING **: 17:12:20.144: Negative content width -7 (allocation 1, extents 4x4) while allocating gadget (node button, owner GtkButton)

(julia.exe:10300): Gtk-WARNING **: 17:12:20.915: Negative content width -5 (allocation 3, extents 4x4) while allocating gadget (node button, owner GtkButton)

(julia.exe:10300): Gtk-WARNING **: 17:12:20.933: Negative content width -2 (allocation 6, extents 4x4) while allocating gadget (node button, owner GtkButton)

(julia.exe:10300): Gtk-WARNING **: 17:12:23.171: Negative content width -7 (allocation 1, extents 4x4) while allocating gadget (node button, owner GtkButton)

(julia.exe:10300): Gtk-WARNING **: 17:12:23.597: Negative content width -4 (allocation 4, extents 4x4) while allocating gadget (node button, owner GtkButton)
```

**Comment by Cruor** [comment]
Thats really weird... Does it happen to other tools as well, or only triggers? Does restarting fix the issue? Have you resized any columns (given the error message), or did it somehow do that by itself?

**Comment by asparagii** [comment]
Just noticed that the "entities" layer only contains two elements?? This is not fixed upon restarting.
(I'm going to update the first message with another screenshot)

**Comment by Cruor** [comment]
At the bottom of the materials there is a search field, do you have anything in it?

**Comment by asparagii** [comment]
Yes, indeed. I just found out that the searchbar stays filled upon restart and that I'm the dumbest human being walking on this earth. Sorry for wasting your time and thanks a lot! 😅

**Comment by Cruor** [comment]
No worries, it happens 👍
