### ISSUE TITLE
Auto hot key conflictions related to "Backup rate"

### ISSUE THREAD

**Issue by anexistantperson** [CelestialCartographers/Ahorn#32]
Disabling "Automatic backups" does not fix the problem, however setting "Backup rate" to an extremely high number does. Setting it to a lower number like 6 causes the player to basically completely loose control over Celeste.

Assuming that "Automatic backups" does actually effect whether Ahorn makes backups or not, it would appear the bug is related to it checking whether it should make a backup or not.

**Comment by Cruor** [comment]
Automatic backup setting not disabling backups has been fixed on develop, but that isn't out yet. Not sure why the backup system would cause any problems with AHK, but I would guess Gtk is doing something funky there.

**Comment by orbittwz** [comment]
by Backup Rate you mean this in the settings of the program?
![image](https://user-images.githubusercontent.com/45605734/126442565-78ccd71d-75da-44b7-96bb-3382aa7e46ac.png)
I always set it to 10 minutes (600 seconds) and the program runs smoothly without getting stuck :)

**Comment by Cruor** [comment]
Fixed in one of the more recent updates, forgot which.
