### ISSUE TITLE
Help, issue

### ISSUE THREAD

**Issue by shananiki** [CelestialCartographers/Ahorn#38]
Activating environment at `C:\Users\steph\AppData\Local\Ahorn\env\Project.toml`
ERROR: LoadError: InitError: IOError: could not spawn setenv(`'C:\Users\steph\.julia\artifacts\57bd9311faafa3d8e73dfb991c2cb420f2c65ab9\bin\gdk-pixbuf-query-loaders.exe'`,["PATH=C:\\Users\\steph\\.julia\\artifacts\\a5b7c195243758d88c64cd8547e527fbace3877b\\bin;C:\\Users\\steph\\.julia\\artifacts\\e5872943f1078a6397a4f4d0f760db959ec50630\\bin;D:\\SteamLibrary\\steamapps\\common\\Celeste\\Julia\\Julia-1.6.0\\bin;C:\\Users\\steph\\.julia\\artifacts\\431cad9bf95e817b5fc813666e353ae36b2202c0\\bin;C:\\Users\\steph\\.julia\\artifacts\\f9f799e6ae3fe7f244bb55052db7ff1cea876c27\\bin;C:\\Users\\steph\\.julia\\artifacts\\4f67e82ee394e74ca63b7dc589dcc9218c12b20a\\bin;C:\\Users\\steph\\.julia\\artifacts\\ac8a1c48a02b397f6ce1beb6473de8bbb3b1e0ce\\bin;C:\\Users\\steph\\.julia\\artifacts\\72037f1415327f12277eed0521c861517630a0ba\\bin;C:\\Users\\steph\\.julia\\artifacts\\2e9a29903fddf79371cd5f82327f70ada670a234\\bin;C:\\Users\\steph\\.julia\\artifacts\\17025344af7bdfe8a7ac4e8887f0953f1dc50376\\bin;C:\\Users\\steph\\.julia\\artifacts\\01b969d96551292e78f0acfa204f120b09f4e7b4\\bin;C:\\Users\\steph\\.julia\\artifacts\\57bd9311faafa3d8e73dfb991c2cb420f2c65ab9\\bin;D:\\SteamLibrary\\steamapps\\common\\Celeste\\Julia\\Julia-1.6.0\\bin\\..\\lib\\julia;D:\\SteamLibrary\\steamapps\\common\\Celeste\\Julia\\Julia-1.6.0\\bin\\..\\lib;D:\\SteamLibrary\\steamapps\\common\\Celeste\\Julia\\Julia-1.6.0\\bin;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\Program Files (x86)\\VMware\\VMware Workstation\\bin\\;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files\\Python310\\Scripts\\;C:\\Program Files\\Python310\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\PuTTY\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Git\\cmd;C:\\scrcpy;C:\\ffmpeg\\bin;C:\\flutter\\bin;C:\\Program Files (x86)\\Gpg4win\\..\\GnuPG\\bin;C:\\curl-7.87.0-win64-mingw\\bin;C:\\Users\\steph\\AppData\\Roaming\\Python\\Python310\\Scripts;C:\\Users\\steph\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\steph\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;D:\\SteamLibrary\\steamapps\\common\\Celeste\\Julia\\Julia-1.6.0\\bin", "USERDOMAIN_ROAMINGPROFILE=msimnotniki", "HOMEPATH=\\Users\\steph", "GDK_PIXBUF_MODULEDIR=C:\\Users\\steph\\.julia\\artifacts\\57bd9311faafa3d8e73dfb991c2cb420f2c65ab9\\lib\\gdk-pixbuf-2.0\\2.10.0\\loaders", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW", "SYSTEMROOT=C:\\Windows", "APPDATA=C:\\Users\\steph\\AppData\\Roaming", "PSMODULEPATH=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules", "GTK_THEME=win32", "PROGRAMDATA=C:\\ProgramData", "COMMONPROGRAMW6432=C:\\Program Files\\Common Files", "DISPLAYHELP=0", "PUBLIC=C:\\Users\\Public", "OS=Windows_NT", "USERDOMAIN=msimnotniki", "PROCESSOR_REVISION=a701", "TMP=C:\\Users\\steph\\AppData\\Local\\Temp", "DARKMODE=0", "COMSPEC=C:\\Windows\\system32\\cmd.exe", "ALLUSERSPROFILE=C:\\ProgramData", "COMPUTERNAME=MSIMNOTNIKI", "USERNAME=msimnotniki", "INSTALL_FILENAME=install_ahorn.jl", "XDG_DATA_DIRS=C:\\Users\\steph\\.julia\\artifacts\\65eca7c48dea1e32203b205613441ce9506045b4\\share;C:\\Users\\steph\\.julia\\artifacts\\eb6ac7b2d830e5142ad5e345e54fb33dc7aafd6c\\share;C:\\Users\\steph\\.julia\\artifacts\\da6c2aa0d20a483437256f245d3c35b25e667c62\\bin\\..\\share", "GTK_CSD=0", "ONEDRIVECONSUMER=C:\\Users\\steph\\OneDrive", "USERPROFILE=C:\\Users\\steph", "GTK_AUTO_IDLE=false", "DEVELOPERMODE=0", "PROCESSOR_LEVEL=6", "INSTALL_URL=https://raw.githubusercontent.com/CelestialCartographers/Ahorn/master/install_ahorn.jl", "PROGRAMW6432=C:\\Program Files", "ONLYUPDATE=0", "HOMEDRIVE=C:", "TEMP=C:\\Users\\steph\\AppData\\Local\\Temp", "WINDIR=C:\\Windows", "LOCALAPPDATA=C:\\Users\\steph\\AppData\\Local", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 167 Stepping 1, GenuineIntel", "UPDATEFIRST=0", "NUMBER_OF_PROCESSORS=12", "PROMPT=\$P\$G", "FONTCONFIG_FILE=C:\\Users\\steph\\.julia\\artifacts\\c916a560fa109a4db3d6938a8ab1a6a8b4a09731\\etc\\fonts\\fonts.conf", "COMMONPROGRAMFILES(X86)=C:\\Program Files (x86)\\Common Files", "AHORN_PATH=C:/Users/steph/AppData/Local/Ahorn", "COMMONPROGRAMFILES=C:\\Program Files\\Common Files", "ONEDRIVE=C:\\Users\\steph\\OneDrive", "PROGRAMFILES(X86)=C:\\Program Files (x86)", "INTEL_DEV_REDIST=C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\", "JULIA_FILENAME=julia-1.6.0-installer.exe", "JULIA_URL_32BIT=https://julialang-s3.julialang.org/bin/winnt/x86/1.6/julia-1.6.0-win32.exe", "OPENBLAS_NUM_THREADS=8", "MINIMUM_VERSION=\"v\\\"1.6.0\\\"\"", "PROGRAMFILES=C:\\Program Files", "LOGONSERVER=\\\\MSIMNOTNIKI", "DRIVERDATA=C:\\Windows\\System32\\Drivers\\DriverData", "FONTCONFIG_PATH=C:\\Users\\steph\\.julia\\artifacts\\c916a560fa109a4db3d6938a8ab1a6a8b4a09731\\etc\\fonts", "AHORN_ENV=\\\"C:/Users/steph/AppData/Local/Ahorn/env/\\\"", "JULIA_URL_64BIT=https://julialang-s3.julialang.org/bin/winnt/x64/1.6/julia-1.6.0-win64.exe", "SYSTEMDRIVE=C:", "=EXITCODE", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_MAIN_FREE=1", "MIC_LD_LIBRARY_PATH=C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\compiler\\lib\\mic"]): invalid argument (EINVAL)
Stacktrace:
  [1] _spawn_primitive(file::String, cmd::Cmd, stdio::Vector{Any})
    @ Base .\process.jl:99
  [2] #637
    @ .\process.jl:112 [inlined]
  [3] setup_stdios(f::Base.var"#637#638"{Cmd}, stdios::Vector{Any})
    @ Base .\process.jl:196
  [4] _spawn
    @ .\process.jl:111 [inlined]
  [5] open(cmds::Cmd, stdio::Base.DevNull; write::Bool, read::Bool)
    @ Base .\process.jl:370
  [6] open
    @ .\process.jl:361 [inlined]
  [7] open(cmds::Cmd, mode::String, stdio::Base.DevNull)
    @ Base .\process.jl:341
  [8] read(cmd::Cmd)
    @ Base .\process.jl:410
  [9] read(cmd::Cmd, #unused#::Type{String})
    @ Base .\process.jl:421
 [10] readchomp
    @ .\io.jl:923 [inlined]
 [11] query_pixbuf_loaders
    @ ~\.julia\packages\Gtk\oo3cW\src\Gtk.jl:101 [inlined]
 [12] (::Gtk.var"#query_pixbuf_loaders#325"{Gtk.var"#query_pixbuf_loaders#320#326"})(dir::String)
    @ Gtk ~\.julia\packages\Gtk\oo3cW\src\Gtk.jl:100
 [13] (::Gtk.var"#321#327")(io::IOStream)
    @ Gtk ~\.julia\packages\Gtk\oo3cW\src\Gtk.jl:106
 [14] open(f::Gtk.var"#321#327", args::String; kwargs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:write,), Tuple{Bool}}})
    @ Base .\io.jl:330
 [15] __init__()
    @ Gtk ~\.julia\packages\Gtk\oo3cW\src\Gtk.jl:104
 [16] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base .\loading.jl:674
 [17] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base .\loading.jl:760
 [18] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:998
 [19] require(uuidkey::Base.PkgId)
    @ Base .\loading.jl:914
 [20] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:901
 [21] include
    @ .\Base.jl:386 [inlined]
 [22] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1050
 [23] require(uuidkey::Base.PkgId)
    @ Base .\loading.jl:914
 [24] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:901
during initialization of module Gtk
in expression starting at C:\Users\steph\.julia\packages\Ahorn\hlYON\src\Ahorn.jl:2

**Comment by Cruor** [comment]
See answer in this issue https://github.com/CelestialCartographers/Ahorn/issues/36
Just going to close this as a duplicate
