### ISSUE TITLE
Link to NSIS installer

### ISSUE THREAD

**Issue by leo60228** [CelestialCartographers/Ahorn#5]
It's currently buried in the pins of #map_making.

**Comment by Tbohley** [comment]
When using NSIS, there are errors "Cannot build..." LibCURL, LightXML, WinRPM, Cairo, Gtk, ZipFile, and MBedTLS. Any fixes?

**Comment by orbittwz** [comment]
Already done year ago!
Closed?

**Comment by orbittwz** [comment]
need to be closed now
