### ISSUE TITLE
Add out-of-bounds check for strawberries (and maybe other entities)

### ISSUE THREAD

**Issue by PenguinOwl** [CelestialCartographers/Ahorn#6]
I recently discovered that collecting a strawberry in a room while another strawberry is out of bounds in the same room crashes the game due to an area indexing error. While this is technical a vanilla mechanic, it is undesirable in almost any conceivable usage of Ahorn. We should probably add either a warning with the option to remove out-of-bound strawberries (and possible other entities mistakenly placed) or just remove them on save.

**Comment by Cruor** [comment]
I am highly against removing anything from a map without the users consent. I agree that this feature should be in, but I don't have a sane way to implement it currently.
Should the user always be warned about all off screen entities? Should entities be marked as "don't warn if outside of room bounds"? How would you maintain and edit such a list, in a user friendly way. 
I have some ideas, but they require loads of refactoring, and this is not currently on the top of the priority list.

**Comment by leo60228** [comment]
What entities would you both want to be out of bounds and don't crash if so? For example, do move blocks crash if out of bounds?

**Comment by leo60228** [comment]
Fixed in 762ba78f54c728f9dda5d28f1b0c7b0057f4e553, please close.
