### ISSUE TITLE
Code fails to build Cartographer Folder and only has two files within the Ahorn folder made.

### ISSUE THREAD

**Issue by Ethy202** [CelestialCartographers/Ahorn#9]
For me, attempting to install the program only downloaded/extracted two items, being Manifest.toml and Project.toml within the "env" folder.

Sidenote: I copied the two files and changed them to txt files to upload them. They may be a way to find the source of the problem.

[Manifest.txt](https://github.com/CelestialCartographers/Ahorn/files/2871671/Manifest.txt)
[Project.txt](https://github.com/CelestialCartographers/Ahorn/files/2871672/Project.txt)

This means the program in it's current state is unusable for many.
It is a common problem, as on the modding section of the Celeste Discord.
It's likely a win7 problem.

**Comment by Ethy202** [comment]
This means the program in it's current state is unusable for many.
It is a common problem, as on the modding section of the Celeste Discord.

**Comment by Vexatos** [comment]
Invalid report.
